name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Tests
      run: |
        echo "Running tests..."
        # You can put: npm test, pytest, etc.

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to ECR
      env:
        ECR_REGISTRY: <your_aws_account_id>.dkr.ecr.us-east-1.amazonaws.com
        IMAGE_REPO_NAME: my-app
      run: |
        IMAGE_TAG=${GITHUB_SHA::7}
        docker build -t $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG
